In [1]:
import pandas as pd
import numpy as np

In [132]:
f = open("/home/share/aschoi/nas/users/asolchoi/data/Drug_Repositioning/6_new_disease/gold_omim_id.txt", 'r')
gold_di = list()
while True:
    line = f.readline()
    if not line: break
    gold_di.append(line.rstrip('\n'))
f.close()

In [109]:
f = open("/home/share/aschoi/nas/users/asolchoi/data/Drug_Repositioning/6_new_disease/HumanDO.obo", 'r')

In [110]:
lines = f.readlines()

In [111]:
data2 = list()
for line in lines:
    if line.startswith('id: DOID:'):
        data2.append(line)
        continue
    if 'xref: OMIM:' in line:
        data2.append(line)
f.close()

In [113]:
def indices(lst, element):
    result = []
    offset = -1
    while True:
        try:
            offset = lst.index(element, offset+1)
        except ValueError:
            return result
        result.append(offset)

In [114]:
do_idx = list()
for idx in range(len(data2)):
    if data2[idx].startswith('id: DO'):
        do_idx.append(idx)

In [115]:
mim_idx = list()
for idx in range(len(data2)):
    if data2[idx].startswith('xref'):
        mim_idx.append(idx)

In [116]:
print len(do_idx)
print len(mim_idx)

10831
4215


In [117]:
data2[75:90]

['id: DOID:0050115\n',
 'id: DOID:0050116\n',
 'id: DOID:0050117\n',
 'id: DOID:0050118\n',
 'id: DOID:0050119\n',
 'id: DOID:0050120\n',
 'id: DOID:0050123\n',
 'id: DOID:0050125\n',
 'xref: OMIM:614371\n',
 'id: DOID:0050126\n',
 'id: DOID:0050127\n',
 'id: DOID:0050129\n',
 'id: DOID:0050130\n',
 'id: DOID:0050131\n',
 'id: DOID:0050132\n']

In [118]:
raw = pd.DataFrame()
for mim in mim_idx:
    temp_df = pd.DataFrame(data=[[data2[mim-1], data2[mim]]], columns=['do_id', 'mim_id'])
    raw = raw.append(temp_df)

In [119]:
raw.index = range(len(raw))

In [120]:
do_idx = raw[raw.do_id.str.contains("id:")].index.values

In [121]:
tmp_idx = raw[raw.do_id.str.contains("xref")].index.values

In [122]:
do_idx[:10]

array([ 0,  1,  2,  3,  4, 15, 16, 17, 18, 19])

In [123]:
tmp_idx[:12]

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 21, 23])

In [124]:
tmp_idx[11] > do_idx[:16]

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True, False, False, False, False], dtype=bool)

In [153]:
tmp = raw
for index in tmp_idx:
    flag = index> do_idx
    setidx = flag.tolist().index(False)
    tmp.set_value(index, 'do_id', tmp['do_id'][4])

In [155]:
tmp.do_id = tmp.do_id.str.lstrip('id: ').str.rstrip('\n')

In [156]:
tmp.mim_id = tmp.mim_id.str.lstrip('xref: ').str.rstrip("\n")

In [162]:
tmp[tmp.mim_id.isin(gold_di)]

do_id       mim_id
18    DOID:0050387  OMIM:144700
20    DOID:0050424  OMIM:175100
22    DOID:0050425  OMIM:102300
35    DOID:0050432  OMIM:300494
60    DOID:0050450  OMIM:263800
103   DOID:0050489  OMIM:138800
133   DOID:0050328  OMIM:608088
339   DOID:0050650  OMIM:607554
340   DOID:0050328  OMIM:608583
398   DOID:0050328  OMIM:308350
437   DOID:0050741  OMIM:103780
442   DOID:0050754  OMIM:208920
445   DOID:0050763  OMIM:208085
452   DOID:0050771  OMIM:171300
538   DOID:0050801  OMIM:109200
563   DOID:0050848  OMIM:107650
572   DOID:0050881  OMIM:167320
652   DOID:0060055  OMIM:119500
679   DOID:0050328  OMIM:300125
681   DOID:0050328  OMIM:607516
684   DOID:0060180  OMIM:191390
1187  DOID:0050328  OMIM:155100
1381  DOID:0060878  OMIM:146255
1503  DOID:0080122  OMIM:203700
1546  DOID:0090004  OMIM:208230
1570  DOID:0090028  OMIM:277460
1582  DOID:0090041  OMIM:128101
1585  DOID:0090044  OMIM:601042
1778  DOID:0110145  OMIM:602522
1940  DOID:0110308  OMIM:115195
...            ...          ...
3894  DOID:0050328  OMIM:311360
3904     DOID:5557  OMIM:273300
3941      DOID:633  OMIM:160750
3943     DOID:6364  OMIM:157300
3954     DOID:6498  OMIM:182000
3957     DOID:6652  OMIM:106400
3964     DOID:6713  OMIM:601367
3976      DOID:718  OMIM:205700
3981      DOID:769  OMIM:256700
3992     DOID:7997  OMIM:275000
3999     DOID:8398  OMIM:140600
4000  DOID:0050328  OMIM:165720
4001  DOID:0050328  OMIM:607850
4008     DOID:8534  OMIM:109350
4010     DOID:8545  OMIM:145600
4012  DOID:0050328  OMIM:154276
4018     DOID:8567  OMIM:236000
4024     DOID:8632  OMIM:148000
4025     DOID:8691  OMIM:254400
4070     DOID:8997  OMIM:263300
4073     DOID:9074  OMIM:152700
4090     DOID:9119  OMIM:601626
4098     DOID:9212  OMIM:173200
4113     DOID:9256  OMIM:114500
4145     DOID:9352  OMIM:125853
4160     DOID:9538  OMIM:254500
4190     DOID:9849  OMIM:156000
4196      DOID:988  OMIM:157700
4208     DOID:9952  OMIM:247640
4214     DOID:9970  OMIM:601665

[154 rows x 2 columns]